### ISSUE TITLE
Bump luigi version to 2.1.1

### ISSUE THREAD

**Issue by DrValani** [axiom-data-science/docker-luigi#2]
Hi 

in requirements.txt you have luigi version >= 2.0.

Version 2.1.1 is out, could you bump it to that please.

Thanks

Yogi

**Comment by kwilcox** [comment]
Was fixed in https://github.com/axiom-data-science/docker-luigi/commit/99b42db06892055102f77c6835e63e5ce852afb1

Bumping to stable now (2.3.1)
